<a href="https://colab.research.google.com/github/pgideon1/Panda-Assignment/blob/main/Panda_NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#Generate an array of zeroes using inbuilt numpy function
import numpy as np
a = np.zeros((3,3))               
print(a)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[3 7 9 9]
 [4 3 9 6]
 [4 7 6 8]]
[[9 6 6]
 [2 3 7]
 [4 2 8]
 [6 6 4]]


In [8]:
a.dot(b)

array([[131, 111, 175],
       [114,  87, 141],
       [122, 105, 153]])

In [9]:
import pandas as pd
data=pd.read_csv('/content/data.csv')
data.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  
0   0.135641  
1   0.080067  
2   0.119868  
3   0.128733  
4   0.125546

In [10]:
data.describe().T

count        mean          std        min        25%         50%  \
OBJECTID     25.0   33.000000     7.359801  21.000000  27.000000   33.000000   
ACRES        25.0  724.134400  1275.490247  11.400000  72.300000  524.810000   
SHAPE.AREA   25.0    0.000352     0.000617   0.000005   0.000034    0.000256   
SHAPE.LEN    25.0    0.109863     0.089073   0.009396   0.033885    0.087192   

                   75%          max  
OBJECTID     39.000000    45.000000  
ACRES       836.470000  6492.930000  
SHAPE.AREA    0.000399     0.003136  
SHAPE.LEN     0.145220     0.338800

In [11]:
data.isna().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

In [12]:
data['DESCRIPTION'].unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [16]:
data.groupby('DESCRIPTION').mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [18]:
i = int(np.random.randint(0,(len(data)-10)))
data.iloc[i:i+10,:]

OBJECTID                                   UNIT_NAME  \
13        36       Crow Flies High State Recreation Area   
14        33                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  
13  State Recreation Area   247.11    0.000120   0.050518  
14             State Park   775.28    0.000378   0.145220  
15             State Park   739.52    0.000357   0.191806  
16     State Natural Area   264.84    0.000127   0.067082  
17  State Recreation Area    21.56    0.000010   0.013294  
18  State Nature Preserve    95.89    0.000048   0.040465  
19  State Nature Preserve    72.30    0.000034   0.033885  
20     State Natural Area   174.39    0.000083   0.087192  
21  State Recreation Area  1236.98    0.000615   0.338800  
22  State Recreation Area   695.04    0.000345   0.086487

In [20]:
new_feature = np.random.rand(25,1)
data['new_feature']=new_feature
data

OBJECTID                                   UNIT_NAME  \
0         21                   Fort Stevenson State Park   
1         22                      Beaver Lake State Park   
2         23             Fort Abraham Lincoln State Park   
3         24                      Fort Ransom State Park   
4         25                   Grahams Island State Park   
5         26                        Icelandic State Park   
6         27                   Lake Metigoshe State Park   
7         28                  Lewis and Clark State Park   
8         29         Lewis and Clark Interpretive Center   
9         30           Fort Mandan State Recreation Area   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
12        35        Butte St. Paul State Recreation Area   
13        36       Crow Flies High State Recreation Area   
14        33                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
23        45                      Cross Ranch State Park   
24        42         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  new_feature  
0              State Park   586.48    0.000284   0.135641     0.106092  
1              State Park   273.16    0.000129   0.080067     0.390414  
2              State Park   836.47    0.000399   0.119868     0.436570  
3              State Park   933.78    0.000444   0.128733     0.426925  
4              State Park   959.33    0.000469   0.125546     0.569720  
5              State Park   930.30    0.000461   0.166712     0.777467  
6              State Park  1508.53    0.000751   0.212196     0.592959  
7              State Park   524.81    0.000256   0.130420     0.293991  
8     Interpretive Center    14.71    0.000007   0.016774     0.681047  
9   State Recreation Area    11.40    0.000005   0.009396     0.375183  
10             State Park  6492.93    0.003136   0.313756     0.373494  
11             State Park    63.03    0.000030   0.024016     0.049683  
12  State Recreation Area    51.23    0.000025   0.022095     0.728527  
13  State Recreation Area   247.11    0.000120   0.050518     0.248720  
14             State Park   775.28    0.000378   0.145220     0.096900  
15             State Park   739.52    0.000357   0.191806     0.950474  
16     State Natural Area   264.84    0.000127   0.067082     0.324080  
17  State Recreation Area    21.56    0.000010   0.013294     0.959073  
18  State Nature Preserve    95.89    0.000048   0.040465     0.655964  
19  State Nature Preserve    72.30    0.000034   0.033885     0.792825  
20     State Natural Area   174.39    0.000083   0.087192     0.744291  
21  State Recreation Area  1236.98    0.000615   0.338800     0.783426  
22  State Recreation Area   695.04    0.000345   0.086487     0.219409  
23             State Park   569.07    0.000274   0.180257     0.348659  
24  State Recreation Area    25.22    0.000013   0.026357     0.865263

In [19]:
data.shape

(25, 6)

In [22]:
data['OBJECTID'].replace(0,data['OBJECTID'].mean(),inplace=True)
data

OBJECTID                                   UNIT_NAME  \
0         21                   Fort Stevenson State Park   
1         22                      Beaver Lake State Park   
2         23             Fort Abraham Lincoln State Park   
3         24                      Fort Ransom State Park   
4         25                   Grahams Island State Park   
5         26                        Icelandic State Park   
6         27                   Lake Metigoshe State Park   
7         28                  Lewis and Clark State Park   
8         29         Lewis and Clark Interpretive Center   
9         30           Fort Mandan State Recreation Area   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
12        35        Butte St. Paul State Recreation Area   
13        36       Crow Flies High State Recreation Area   
14        33                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
23        45                      Cross Ranch State Park   
24        42         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  new_feature  
0              State Park   586.48    0.000284   0.135641     0.106092  
1              State Park   273.16    0.000129   0.080067     0.390414  
2              State Park   836.47    0.000399   0.119868     0.436570  
3              State Park   933.78    0.000444   0.128733     0.426925  
4              State Park   959.33    0.000469   0.125546     0.569720  
5              State Park   930.30    0.000461   0.166712     0.777467  
6              State Park  1508.53    0.000751   0.212196     0.592959  
7              State Park   524.81    0.000256   0.130420     0.293991  
8     Interpretive Center    14.71    0.000007   0.016774     0.681047  
9   State Recreation Area    11.40    0.000005   0.009396     0.375183  
10             State Park  6492.93    0.003136   0.313756     0.373494  
11             State Park    63.03    0.000030   0.024016     0.049683  
12  State Recreation Area    51.23    0.000025   0.022095     0.728527  
13  State Recreation Area   247.11    0.000120   0.050518     0.248720  
14             State Park   775.28    0.000378   0.145220     0.096900  
15             State Park   739.52    0.000357   0.191806     0.950474  
16     State Natural Area   264.84    0.000127   0.067082     0.324080  
17  State Recreation Area    21.56    0.000010   0.013294     0.959073  
18  State Nature Preserve    95.89    0.000048   0.040465     0.655964  
19  State Nature Preserve    72.30    0.000034   0.033885     0.792825  
20     State Natural Area   174.39    0.000083   0.087192     0.744291  
21  State Recreation Area  1236.98    0.000615   0.338800     0.783426  
22  State Recreation Area   695.04    0.000345   0.086487     0.219409  
23             State Park   569.07    0.000274   0.180257     0.348659  
24  State Recreation Area    25.22    0.000013   0.026357     0.865263